# Generated by Django 5.0.3 on 2024-03-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('F', 'food'), ('NF', 'not food')], default='NF'),
        ),
    ]
